{
 "title": "New dashboard",
 "time": { "from": "2025-05-02T13:49:50.994Z", "to": "2025-05-02T13:54:37.714Z" },
 "panels": [
  {
   "title": "total request count per path",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "testpath_requests_total", "legendFormat": "{{path}}" }
   ]
  },
  {
   "title": "rate() function",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "rate(testpath_requests_total[5m])",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "irate() function",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "irate(testpath_requests_total[5m])",
     "legendFormat": "{{path}}"
    }
   ]
  }
 ]
}